[package]
name = "drunken-bishop"
version = "0.1.0"
authors = ["AbsurdlySuspicious <repom2@airmail.cc>"]
edition = "2018"
publish = false

license = "Apache-2.0/MIT"

[dependencies]
unicode-width = "0.1.6"
custom_error = "1.7.1"
hex = "0.3.2"
structopt = "0.3"
