edition = "2018"
unstable_features = true
tab_spaces = 4
indent_style = "Visual"
single_line_if_else = true
#use_small_heuristics = "Max"
enum_discrim_align_threshold = 25
struct_field_align_threshold = 25
control_brace_style = "ClosingNextLine"
fn_single_line = true
fn_args_layout = "Tall"

